language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - hhvm

sudo: false

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

addons:
  apt:
    packages:
      - nginx
      - realpath
  hosts:
    - vanilla.test

install:
  - composer self-update
  - composer install -o
  - composer require phpunit/phpunit ~5
  - tests/travis/setup.sh

script:
  - touch /tmp/custom.log
  - ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage.clover
  - cat /tmp/error.log
  - cat /tmp/access.log
  - cat /tmp/custom.log
